# three node (two workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    # kubeadmConfigPatches:
    #   - |
    #     kind: InitConfiguration
    #     localAPIEndpoint:
    #       advertiseAddress: "127.0.0.1"
    #       bindPort: 49801  # change from 49800
    extraPortMappings:
      - containerPort: 30000
        hostPort: 30000
        listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
        protocol: tcp # Optional, defaults to tcp
      - containerPort: 31321
        hostPort: 31321
      - containerPort: 31300
        hostPort: 31300
  - role: worker
  - role: worker
